### ISSUE TITLE
添加二维码水印

### ISSUE THREAD

**Issue by w2xx** [ZanderChang/DigitalWatermark#4]
你好，使用demo的时候，在添加二维码水印时，部分图片会出现一定概率的提取水印失败

**Comment by ZanderChang** [comment]
嗯嗯，我们当时发现和拍照光线有关。

**Comment by w2xx** [comment]
那这个有没有解决办法呀。。我用了另一种添加图片水印，但是提取出来的图片有噪点呢

**Comment by ZanderChang** [comment]
当时做的很匆忙……后来也没有继续维护了...

**Comment by w2xx** [comment]
而且，在华为上，二维码水印很大概率提取不出来。。这个能否帮忙看下解决，可以有偿，非常感谢

**Comment by ZanderChang** [comment]
我们测试的机器是魅族mx的一款...我现在不做水印这一块了…抱歉帮不到你了..

**Comment by w2xx** [comment]
那好吧。。多谢
